/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inv.com.me.shop;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/* @author shantanu */
public class AllDues extends javax.swing.JFrame {

    DefaultTableModel duesModel;

    /**
     * Creates new form AllDues
     */
    public AllDues() {
        initComponents();
        amountPanel.setVisible(false);
        setVisible(true);
        fillTable();
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            //System.out.println(table.getValueAt(table.getSelectedRow(), 0).toString());
            amountPanel.setVisible(true);
            amountTv.setText("");
        }
    });
      
    }

    public void fillTable() {
        JSONArray array = JsonClass.getJsonArray(Constants.DUES_FILE);
        if(array.size()==0){
            duesModel.addRow(new Object[] {"","No Dues Record Available","","",""});
        }
        for (int i = 0; i < array.size(); i++) {
            JSONObject obj = (JSONObject) array.get(i);
            String dues = obj.get("dues").toString();
            String cId = obj.get("customerId").toString();
            String days = obj.get("days").toString();
            String billDate = obj.get("billDate").toString();
            String cName = obj.get("customerName").toString();

            Date dueDate = DateCompare.getDateDaysAfter(billDate, days);
           
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String d = sdf.format(dueDate);
            
            duesModel.addRow(new Object[] {cId, cName, dues, billDate, d});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        amountPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        amountTv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(600, 270));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "All Dues", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N

        duesModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Dues", "Bill Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(duesModel);
        table.setRowHeight(40);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMaxWidth(250);
            table.getColumnModel().getColumn(2).setMaxWidth(300);
        }
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Amount : ");

        amountTv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout amountPanelLayout = new javax.swing.GroupLayout(amountPanel);
        amountPanel.setLayout(amountPanelLayout);
        amountPanelLayout.setHorizontalGroup(
            amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(amountPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(amountTv, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        amountPanelLayout.setVerticalGroup(
            amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, amountPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(amountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(amountTv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Paid");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(amountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(table.getSelectedRow() != -1){
           if(amountTv.getText().equals("")){
               AlertMessage msg = new AlertMessage("Please specify the amount paid");
           }else if(!Helper.priceFormatCheck(amountTv.getText())){
               AlertMessage msg = new AlertMessage("Paid amount is not in correct format");
           }else{
               String id = table.getValueAt(table.getSelectedRow(), 0).toString();
               updateValueInDuesFile(id, amountTv.getText());
               
               
           }
       }else{
           AlertMessage msg = new AlertMessage("Please select the customer who paid you");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void updateValueInDuesFile(String id, String amt){
        JSONArray array = JsonClass.getJsonArray(Constants.DUES_FILE);
        Main.updateHistory(Float.parseFloat(amt), "paid", id);
        for(int i=0;i<array.size();i++){
            JSONObject obj = (JSONObject) array.get(i);
            String cId = obj.get("customerId").toString();
        
            if(cId.equals(id)){
                float dues = Float.parseFloat(obj.get("dues").toString());
                if(Float.parseFloat(amt) >= dues || Math.abs(Float.parseFloat(amt)-dues)<1){
                    removeFromDuesList(id);
                    if(Math.abs(Float.parseFloat(amt)-dues) > 1){
                        AlertMessage msg = new AlertMessage("<html>Dues cleared..!!<br><br>Please return "+(Float.parseFloat(amt) - dues)+"</html>");
                    }else{
                        AlertMessage msg = new AlertMessage("Dues cleared..!!");
                    }
                }else{
                    updateDuesList(id, Float.parseFloat(amt));
                    AlertMessage msg = new AlertMessage("<html>Dues updated..!!<br><br>Rs "+(dues-Float.parseFloat(amt))+"  more is left as dues</html>");
                }
                duesModel.setNumRows(0);
                fillTable();
            }
        }
    }

    public void removeFromDuesList(String id){
        JSONArray newArray = new JSONArray();
        JSONArray array = JsonClass.getJsonArray(Constants.DUES_FILE);
        for(int i=0;i<array.size();i++){
            JSONObject obj = (JSONObject) array.get(i);
            String gotId = obj.get("customerId").toString();
            if(!gotId.equals(id)){
                newArray.add(obj);
            }
        }
        FileWriter.write(Constants.DUES_FILE, newArray.toString());
    }
    public void updateDuesList(String id, float amt){
        JSONArray newArray = new JSONArray();
        JSONArray array = JsonClass.getJsonArray(Constants.DUES_FILE);
        for(int i=0;i<array.size();i++){
            JSONObject obj = (JSONObject) array.get(i);
            String gotId = obj.get("customerId").toString();
            if(gotId.equals(id)){
                float dues  = Float.parseFloat(obj.get("dues").toString());
                obj.replace("dues", dues - amt);
                newArray.add(obj);
                
            }else{
                newArray.add(obj);
            }
        }
        FileWriter.write(Constants.DUES_FILE, newArray.toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amountPanel;
    private javax.swing.JTextField amountTv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
